#! /bin/sh
### BEGIN INIT INFO
# Provides:          samurai
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run commands at boot depending on running live DVD or installed version
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
	echo "Samurai init.d script ran" > /tmp/samurai.init
        if [ "`cat /proc/cmdline | grep casper`" = "" ]; then
            # Commands that run if installed to harddrive
	    echo

        else
            # Commands that run if running live DVD
            cp /etc/hosts.samurai /etc/hosts
	    cp /etc/hostname.samurai /etc/hostname
	    hostname samurai-wtf
	    # disable SSH & create new SSH keys
	    update-rc.d -f ssh remove
	    /usr/bin/sshd-generate > /dev/null 2>&1
        fi
} 

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

